[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.4.1",
    "evaluate>=0.4.6",
    "hf-transfer>=0.1.9",
    "numpy>=2.3.5",
    "pip>=25.3",
    "peft>=0.18.0",
    "torch>=2.9.1",
    "transformers>=5.0.0rc1",
    "sentencepiece>=0.2.1",
    "sacrebleu>=2.5.1",
    "protobuf>=6.33.1",
    "trl>=0.24.0",
    "bitsandbytes>=0.49.0",
    "mistral-common>=1.8.6",
    "tokenizers>=0.22.1",
    "tiktoken>=0.12.0",
    "unsloth>=2025.12.6",
    "unsloth-zoo>=2025.12.5",
]



# target torch to cuda 12.8 or CPU
[tool.uv.sources]
torch = [  
    { index = "pytorch-cpu", extra = "cpu" },  
    { index = "pytorch-cu128", extra = "gpu" },  
]

[[tool.uv.index]]  
name = "pytorch-cpu"  
url = "https://download.pytorch.org/whl/cpu"  
explicit = true  
  
[[tool.uv.index]]  
name = "pytorch-cu128"  
url = "https://download.pytorch.org/whl/cu128"  
explicit = true


[project.optional-dependencies]  
cpu = [  
    "torch>=2.8.0",  
]  
gpu = [  
    "torch>=2.8.0",  
]  


[tool.uv]  
conflicts = [  
    [  
        { extra = "cpu" },  
        { extra = "gpu" },  
    ],  
]  
